Ubuntu_16.04/resources/gitRepo/providers/_bitbucket.sh, Ubuntu_16.04/resources/gitRepo/providers/_gerrit.sh, Ubuntu_16.04/resources/gitRepo/providers/_github.sh, Ubuntu_16.04/resources/gitRepo/providers/_gitlab.sh
https://github.com/Shippable/pm/issues/11943
=> Add gitRepo clone scripts

_common/header.sh, steps/runSh/execute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/3
=> add onExecute.sh template

steps/bash/00_setup/runtime/image/auto/auto.sh, steps/bash/00_setup/runtime/image/auto/language/nodejs.sh, steps/bash/00_setup/runtime/image/custom/custom.sh, steps/bash/00_setup/runtime/image/image.sh, steps/bash/00_setup/runtime/runtime.sh, steps/bash/00_setup/setup.sh
https://github.com/Shippable/kermit-execTemplates/issues/6
https://github.com/Shippable/kermit-execTemplates/issues/7
=> support container build on default, auto, custom

steps/bash/00_setup/runtime/runtime.sh
https://github.com/Shippable/kermit-execTemplates/issues/7
=> image supports auto/custom type

_common/header.sh, steps/bash/00_setup/runtime/image/auto/auto.sh, steps/bash/00_setup/runtime/image/custom/custom.sh, steps/bash/00_setup/runtime/runtime.sh, steps/bash/bash.sh
https://github.com/Shippable/kermit-execTemplates/issues/7
=> fix logic for booting up default container

_common/header.sh, steps/bash/00_setup/runtime/image/auto/auto.sh, steps/bash/00_setup/runtime/image/custom/custom.sh, steps/bash/00_setup/runtime/runtime.sh, steps/bash/01_execution/onComplete/onComplete.sh, steps/bash/01_execution/onFailure/onFailure.sh, steps/bash/01_execution/onSuccess/onSuccess.sh, steps/bash/bash.sh
https://github.com/Shippable/pm/issues/12038
=> run onSuccess, onFailure, onComplete only once

_common/header.sh
#14 
Confirmed both are available.  The only change is that `read_json` will now exit with an error if the file does not exist.
=> #14; copies bump_semver and read_json.

_common/header.sh
#16 
Adds `encrypt_file` and `decrypt_file`.  Tested by encrypting and decrypting a short file with a PEM key.
=> #16; adds encrypt_file and decrypt_file.

_common/header.sh
=> add replace_tags for ENVs

_common/header.sh
#20 
Tested encoding and decoding a string.
=> #20; adds encrypt_string and decrypt_string.

_common/header.sh
=> initial tag support for replace_tags

_common/header.sh
=> use replace_tags in exec_cmd

_common/header.sh
#26 
Checked that the correct changed file is found for both `--resource` and `--path --commit-range`.
=> #26; copies git_changes.

steps/bash/header.sh
#30 
Doesn't copy files or the webhook header and body because we aren't saving those.  Tested by checking the data was copied (or not) to the file correctly with gitRepos with and without matching settings.
=> #30; copies replicate_resource.

steps/bash/00_setup/00_environmentVariables/footer.sh, steps/bash/00_setup/00_environmentVariables/header.sh, steps/bash/01_execution/00_onStart/footer.sh, steps/bash/01_execution/00_onStart/header.sh, steps/bash/01_execution/01_onExecute/footer.sh, steps/bash/01_execution/01_onExecute/header.sh, steps/bash/header.sh
=> add startstop group

steps/bash/setup/runtime/image/image.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/40
=> use imageName:imageTag

steps/bash/header.sh
#42 
Copies `send_notification`.  Checked that payloads are generated for NewRelic, Airbrake, and Jira and that Slack and webhooks work.  IRC was not copied because there is no account-level IRC integration.
This also copies `replace_envs` because it is used by `send_notification`.
=> #42; copies send_notification.

steps/bash/header.sh
#44 
Adds `write_output` and uses the new path in `step.json` for `compare_git`.
Examples:
`write_output resourceName --separator , key1,value1,key2,value2`
`write_output resourceName key1 value1 key2 value2`
=> #44; adds write_output.

steps/bash/header.sh
#48 
Adds Go to `switch_env`.  Tested with a version already on the image and a version not.
=> #48; adds Go to switch_env.

steps/bash/header.sh
#49 
Adds Python to `switch_env`, and checks if the Python path exists before trying to set up `virtualenv`.
=> #49; adds Python to switch_env.

steps/bash/header.sh
#50 
Adds NodeJS to `switch_env`.  Tested with a version already installed and one not.
=> #50; adds NodeJS to switch_env.

steps/bash/header.sh
#52 
Copies PHP to `switch_env`.
=> #52; copies PHP to switch_env.

steps/bash/execution/onExecute/onExecute.sh, steps/bash/execution/onStart/onStart.sh, steps/bash/header.sh, steps/bash/setup/runtime/image/image.sh
=> enhance start and stop group

steps/bash/header.sh
=> remove exec_cmd and exec_grp

steps/bash/header.sh
#26 
Removes unnecessary variable assignment.
=> Removes extra variable assignment.

steps/bash/header.sh
=> defaults for enc/dc and new default payload for webhook notifications

steps/bash/setup/environmentVariables/environmentVariables.sh, steps/bash/setup/environmentVariables/footer.sh, steps/bash/setup/environmentVariables/header.sh
https://github.com/Shippable/kermit-execTemplates/issues/71
=> escape strings inside double quotes

steps/bash/setup/environmentVariables/environmentVariables.sh
https://github.com/Shippable/kermit-execTemplates/issues/74
=> export readonly envs

steps/bash/setup/runtime/image/image.sh
#77 
Updates task container volume mounts.  The new variables will also be added in kermit-reqProc.
=> #77; updates task container volume mounts.

steps/bash/setup/runtime/image/auto/auto.sh
https://github.com/Shippable/pm/issues/12132
=> update execTemplate to set language version

steps/bash/header.sh
#83 
A file will be restored to the path specified.  A directory's contents will be copied into a directory at the path specified.  It also checks for spaces in the cache names now; a space in the name was likely to lead to errors.
=> #83; adds restore_cache.

resources/gitRepo/gitRepo.sh
https://github.com/Shippable/kermit-execTemplates/issues/89
merge this after https://github.com/Shippable/kermit-reqProc/pull/100
=> adds gitRepo resource template

steps/bash/header.sh
#95 
Nearly identical to the functions for step cache.
=> #95; adds save_run_state and restore_run_state.

resources/gitRepo/dependsOn.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/89
=> use dependsOn.sh

resources/gitRepo/dependsOn.sh
https://github.com/Shippable/kermit-execTemplates/issues/89
=> set http.sslVerify before cloning the repo

steps/bash/setup/runtime/image/image.sh
=> path changes

steps/bash/header.sh
=> Use url instead of webhookUrl for Slack integration

resources/gitRepo/dependsOn.sh
=> dont use gitRepo dir

steps/bash/header.sh
=> fix compare_git for new repo path

resources/state/output.sh
#109 
Adds an `output` script for state resources.  Confirmed that the files are uploaded when a filestore provider is configured.
=> #109; adds output script for state resources.

resources/state/dependsOn.sh
#115 
Adds `IN` script for state resources.  Confirmed that a file can be stored in an `OUT` state resource for one step and used as an `IN` in another step.
=> #115; adds dependsOn.sh for state resources.

steps/bash/header.sh
#117 
Just like the functions for run state, but with an extra parameter (resource) and a different location (resource path). Tested with an individual file and a wildcard matching multiple files.
=> #117; adds save_resource_state and restore_resource_state.

steps/bash/setup/environmentVariables/environmentVariables.sh
https://github.com/Shippable/kermit-execTemplates/issues/119
=> export envs without enclosing value inside double quotes

resources/gitRepo/dependsOn.sh
#123 
Adds Bitbucket similar to the one in reqProc for Assembly Lines to be consistent with the existing GitHub script.
=> #123; adds Bitbucket to gitRepo.

resources/gitRepo/dependsOn.sh
#124 
Adds bitbucketServerBasic to the gitRepo `dependsOn` script.
=> #124; adds Bitbucket Server to gitRepo.

resources/image/dependsOn.sh
https://github.com/Shippable/kermit-execTemplates/issues/121
verified the script exporting all the envs.
=> adding execTemplate script for image resource processing

resources/file/dependsOn.sh
https://github.com/Shippable/heap/issues/2999
manually populated the int envs and verified fetching file
=> execTemplates script to fetch file from s3 and gcloud

resources/image/dependsOn.sh
https://github.com/Shippable/heap/issues/2973
as we will be only using latest version of jfrog. removing that logic to check the version
=> remove checking jfrog version as we will be using latest version

steps/bash/setup/runtime/image/image.sh
https://github.com/Shippable/pm/issues/12257
=> use STEP_DOCKER_CONTAINER_NAME

resources/cluster/dependsOn.sh
https://github.com/Shippable/pm/issues/12272
=> execTemplates script to process cluster resource

steps/pushToArtifactory/execution/onExecute/onExecute.sh, steps/pushToArtifactory/pushToArtifactory.sh
=> Add push to artifactory

resources/file/dependsOn.sh
https://github.com/Shippable/pm/issues/12280
=>  update resource/file/dependsOn.sh to download file from s3

resources/file/dependsOn.sh
https://github.com/Shippable/pm/issues/12282
=> update resource/file/dependsOn.sh to download file from google cloud

resources/file/dependsOn.sh
https://github.com/Shippable/pm/issues/12287
=> update resource/file/dependsOn.sh to download file from artifactory

resources/file/dependsOn.sh
https://github.com/Shippable/pm/issues/12289
=> update resource/file/dependsOn.sh to download file from fileServer(FTP)

steps/bash/header.sh
https://github.com/Shippable/pm/issues/12132
=> correct nodejs language name

resources/webhook/output.sh
https://github.com/Shippable/pm/issues/12315
=> Add out handling for external webhook resource

steps/push/execution/onExecute/onExecute.sh
=> Update push template

steps/bash/header.sh
#146 
Updates the commit status on GitHub.  Other providers are not yet supported.
=> #146; adds update_commit_status for GitHub.

resources/state/dependsOn.sh, resources/state/output.sh
- https://github.com/Shippable/kermit/issues/1448
=> using url options, if avaiable

resources/image/dependsOn.sh, steps/push/execution/onExecute/onExecute.sh
=> Enhance push step to work with new DSL

resources/file/dependsOn.sh, steps/push/execution/onExecute/onExecute.sh
=> Allow file push

resources/file/dependsOn.sh, steps/push/execution/onExecute/onExecute.sh
=> Add push support for s3, gcloud and ftp

steps/bash/setup/runtime/image/auto/auto.sh
=> #161; puts auto.sh in a console group.

steps/bash/validate.json, steps/push/validate.json
=> Add JSON schema for bash and push

resources/gitRepo/dependsOn.sh
#167 
Confirmed that a private git repository can be cloned.  This will also not change the settings for any other SSH actions.
=> #167; adds StrictHostKeyChecking=no to gitRepo inputs.

steps/bash/header.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/170
=> set HOME env, if not set

steps/bash/header.sh, steps/bash/setup/runtime/image/image.sh
#173 
Adds new header functions for pipeline state and a volume mount so that it will be available when running in a container.  Almost identical copies of the functions for run state.
=> #173; adds new pipeline state header functions.

resources/buildInfo/validate.json
=> Add JSON schema for buildInfo resource

resources/promoteInfo/validate.json
=> Add JSON schema for promoteInfo resource

steps/promote/execution/onExecute/onExecute.sh, steps/promote/validate.json
=> Add template and schema for promote step

steps/bash/header.sh
#187 
Changes the color depending on the section and alters the default text.
=> #187; updates default Slack color and text.

steps/bash/header.sh
=> add email support in send_notification

steps/promote/execution/onExecute/onExecute.sh
=> Enhance promote script

steps/bash/header.sh
closes #193
also switches from step to steplet
=> support attaching logs

steps/bash/header.sh
=> support showing failing commands

steps/bash/header.sh
=> support body and subject

steps/bash/header.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/203
=> Removing _set_nodejs form header.sh file

steps/bash/header.sh
=> support attachments up to 5MB total

steps/bash/validate.json, steps/promote/validate.json, steps/push/validate.json
https://github.com/Shippable/pm/issues/12468
=> Allow chronological flag to be added in configurations

resources/gitRepo/dependsOn.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/206
=> save git details gets in jfrog build-info

steps/powershell/execution/onExecute/onExecute.ps1, steps/powershell/header.ps1, steps/powershell/setup/environmentVariables/environmentVariables.ps1, steps/powershell/setup/environmentVariables/footer.ps1, steps/powershell/setup/environmentVariables/header.ps1
https://github.com/Shippable/kermit-execTemplates/issues/208
=> Adds environment variables support for powershell step

resources/file/dependsOn.sh
https://github.com/Shippable/pm/issues/12476
Tested for pattern and flag specs.
=> update file resources IN handler to download artifacts using file specs

resources/file/dependsOn.sh
https://github.com/Shippable/pm/issues/12476
=> set limit and offset specs as integer

resources/file/dependsOn.sh
https://github.com/Shippable/pm/issues/12476
=> add build-info to downloaded artifacts

steps/publish/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/216
=> adds validation for publish

resources/buildInfo/validate.json, resources/promoteInfo/validate.json
https://github.com/Shippable/kermit/issues/1670
=> renames initialVersion to version in validate.json

steps/push/validate.json
https://github.com/Shippable/pm/issues/12485
=> remove payloadType from push step

steps/build/execution/onExecute/onExecute.sh, steps/build/validate.json
=> Add templates for build step

steps/build/execution/onExecute/onExecute.sh
=> Save jfrog CLI state to pipeline

steps/build/validate.json
=> Add payloadType, setup as required props for build

steps/build/execution/onExecute/onExecute.sh
=> Use run state instead of pipeline in build step

steps/push/execution/onExecute/onExecute.sh, steps/push/validate.json
https://github.com/Shippable/pm/issues/12485
=> update push step handler to use buildStepName_* envs

steps/build/execution/onExecute/onExecute.sh, steps/publish/execution/onExecute/onExecute.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/224
=> adds template for publish

steps/push/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12485
=> use correct env for build number

steps/promote/execution/onExecute/onExecute.sh, steps/promote/validate.json
=> Update promote validation and template

steps/build/execution/onExecute/onExecute.sh, steps/publish/execution/onExecute/onExecute.sh, steps/push/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12486
=> don't copy jfrog folder again

steps/promote/execution/onExecute/onExecute.sh
=> Promote dependencies in promote

steps/promote/execution/onExecute/onExecute.sh
=> Promote dependencies in promote (for real)

resources/gitRepo/validate.json
#232 
Adds JSON validation file for gitRepo resources.
=> #232; adds gitRepo validation JSON.

steps/bash/validate.json
=> #234; adds autoPull to bash validator.

steps/bash/header.sh
=> support jira api v3

steps/promote/execution/onExecute/onExecute.sh, steps/promote/validate.json
=> Support includeDependencies flag for promote

resources/gitRepo/dependsOn.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/242
=> run jfrog rt bag if jfrog cli is present

steps/scan/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/245
=> adds validation for scan

resources/releaseBundle/validate.json
=> Add validate.json for releaseBundle resource

steps/scan/execution/onExecute/onExecute.sh, steps/scan/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/249
=> scan native step

steps/publish/execution/onExecute/onExecute.sh, steps/publish/validate.json, steps/push/execution/onExecute/onExecute.sh, steps/push/validate.json, steps/scan/execution/onExecute/onExecute.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/251
closes https://github.com/Shippable/kermit-execTemplates/issues/252
closes https://github.com/Shippable/kermit-execTemplates/issues/253
closes https://github.com/Shippable/kermit-execTemplates/issues/254
closes https://github.com/Shippable/kermit-execTemplates/issues/255
=> publish, scan from push/publish steps

resources/aql/validate.json
=> Add validate.json for aql resource

resources/DistributionRule/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/259
=> adds validation schema for DistributionRule

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/CreateReleaseBundle/validate.json
For `aql` resources this is not populating mappings and added_properties. will do that later.
sample payload:
```
{
"name": "ankul-test-release",
"version": "v1.0.1",
"spec": {
"source_artifactory_id": "",
"queries": [
{
"aql": "items.find({ \"$and\": [ { \"$or\": [ { \"repo\": { \"$eq\": \"docker-virtual\" } }{ \"repo\": { \"$eq\": \"docker-virtual\" } } ] }, { \"$or\": [ { \"$and\": [ { \"artifact.module.build.name\": { \"$eq\": \"native_pipeline\" } }, { \"artifact.module.build.number\": { \"$eq\": \"11\" } } ] } , { \"$and\": [ { \"artifact.module.build.name\": { \"$eq\": \"native_pipeline\" } }, { \"artifact.module.build.number\": { \"$eq\": \"12\" } } ] } ] } ] } ).include(\"sha256\",\"updated\",\"modified_by\",\"created\", …
```
=> User can add and use a createReleaseBundle step to create release bundles

steps/SignReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/validate.json
https://github.com/Shippable/pm/issues/12515
=> add validate.json and exec handler for SignReleaseBundle step

steps/Distribute/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/265
=> adds validation for Distribute step

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12515
=> Fail step if distribution API call fails

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12515
=> do not log complete response from API on success

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/execution/onExecute/onExecute.sh
=> populate releaseNotes correctly

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
=> add added properties to payload to create release bundle API call

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
=> Remove backslashes from the key

steps/bash/header.sh
=> update STEP_ID references to step_id

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/execution/onExecute/onExecute.sh, steps/bash/header.sh, steps/build/execution/onExecute/onExecute.sh
Also verified by running a build type step
=> update STEP_NAME references to step_name

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
=> Set mappings in payload if provided in aql resource

steps/bash/header.sh
=> update STEP_URL references to step_url

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/bash/header.sh, steps/build/execution/onExecute/onExecute.sh, steps/promote/execution/onExecute/onExecute.sh, steps/publish/execution/onExecute/onExecute.sh, steps/push/execution/onExecute/onExecute.sh, steps/scan/execution/onExecute/onExecute.sh
=> update STEP_JSON_PATH references to step_json_path

steps/bash/setup/runtime/image/image.sh
=> update STEPLET_SCRIPT_PATH references to steplet_script_path

steps/bash/header.sh, steps/bash/setup/runtime/image/image.sh, steps/powershell/header.ps1
=> update RUN_DIR references to run_dir

steps/bash/header.sh
=> update STEP_WORKSPACE_DIR references to step_workspace_dir

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
=> do not add mappings in payload if not set in resource version

resources/file/dependsOn.sh, resources/gitRepo/dependsOn.sh, steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/execution/onExecute/onExecute.sh, steps/bash/header.sh, steps/bash/setup/runtime/image/image.sh, steps/powershell/header.ps1
=> update PIPELINE_WORKSPACE_DIR references to pipeline_workspace_dir

steps/GoBuild/execution/onExecute/onExecute.sh, steps/GoBuild/validate.json
=> Add schema and template for GoBuild

resources/file/dependsOn.sh, resources/gitRepo/dependsOn.sh, steps/bash/execution/onComplete/header.sh, steps/bash/execution/onExecute/header.sh, steps/bash/execution/onFailure/header.sh, steps/bash/execution/onStart/header.sh, steps/bash/execution/onSuccess/header.sh, steps/bash/header.sh, steps/bash/setup/runtime/image/image.sh, steps/build/execution/onExecute/onExecute.sh, steps/powershell/execution/onComplete/header.ps1, steps/powershell/execution/onExecute/header.ps1, steps/powershell/execution/onFailure/header.ps1, steps/powershell/execution/onStart/header.ps1, steps/powershell/execution/onSuccess/header.ps1
=> update envs to lower case

steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh, steps/DistributeReleaseBundle/validate.json
https://github.com/Shippable/heap/issues/3087
=> Distribute -> DistributeReleaseBundle

resources/Webhook/output.sh
=> use correct int reference

resources/BuildInfo/validate.json
=> Update validation for BuildInfo

resources/GitRepo/validate.json
https://github.com/Shippable/pm/issues/12583
=> update gitRepo validate.json for new yml syntax

resources/ReleaseBundle/validate.json
=> Update JSON schema for ReleaseBundle

resources/DistributionRule/validate.json
=> Add JSON schema for DistributionRule

resources/GitRepo/validate.json
https://github.com/Shippable/pm/issues/12583
=> remove repoPath from required properties for gitRepo

resources/VmCluster/validate.json
=> Add JSON schema for VmCluster

resources/Aql/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/310
=> update Aql validation schema

resources/Image/dependsOn.sh, resources/KubeCluster/dependsOn.sh, resources/RemoteFile/dependsOn.sh, steps/bash/header.sh
#312
This actually updates all of execTemplates to use the new integrationAlias value.
=> use alias instead of _int_

steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh
=> DistributionRule enhancements

steps/bash/header.sh
#320 
Changes `except` to `exclude` and `only` to `include`.
=> #320; update replicate_resource except/only.

resources/FileSpec/validate.json
https://github.com/Shippable/heap/issues/3262 for reference:
```
resources:
- name: fileSpecResource
type: FileSpec
configuration:      
sourceArtifactory: artifactoryIntegration
pattern: <string> # optional
aql: <string> # optional
target: <string> # optional
props: <string> # optional
recursive: <boolean> # optional
flat: <boolean> # optional
excludePatterns: <string> # optional
archiveEntries: <string> # optional
sortBy: <string> # optional
sortOrder: <string> # optional
limit: <integer> # optional
offset: <integer> # optional
```
=> updates FileSpec validate JSON

steps/NpmBuild/validate.json
https://github.com/Shippable/pm/issues/12605
=> Add validate.json for NpmBuild type steps

steps/NpmBuild/validate.json
https://github.com/Shippable/pm/issues/12605
=> correct repositoryName type

steps/Bash/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/327
=> updates schema validation for bash

steps/PublishBuildInfo/execution/onExecute/onExecute.sh, steps/PublishBuildInfo/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/330
=> update PublishBuildInfo validate.json to use the new yaml structure

steps/MvnBuild/execution/onExecute/onExecute.sh, steps/MvnBuild/validate.json
=> Add JSON schema and script for MvnBuild

steps/MvnBuild/validate.json
=> Add sourceLocation to required in MvnBuild

steps/NpmBuild/validate.json
https://github.com/Shippable/pm/issues/12605
=> update NpmBuild steps validate.json for new syntax

steps/Bash/validate.json, steps/CreateReleaseBundle/validate.json, steps/MvnBuild/validate.json, steps/NpmBuild/validate.json, steps/PublishBuildInfo/validate.json
https://github.com/Shippable/pm/issues/12613
=> upadtes validate JSON for CreateReleaseBundle step

steps/XrayScan/validate.json
https://github.com/Shippable/pm/issues/12619
=> updates validation for XrayScan

steps/DistributeReleaseBundle/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/341
=> updates validation for DistributeReleaseBundle

steps/PromoteBuild/validate.json, steps/PublishBuildInfo/validate.json
https://github.com/Shippable/pm/issues/12615
=> update PromoteBuild validate.json to use the new yaml structure

steps/PromoteBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12615
I missed renaming promote -> PromoteBuild in this file  yesterday
=> rename promote -> PromoteBuild

steps/DockerBuild/execution/onExecute/onExecute.sh, steps/DockerBuild/validate.json
=> Update JSON schema and template for DockerBuild

steps/NpmBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12605
=> add onExecute.sh for processing NpmBuild steps

steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/349
=> uses correct envs for countryCodes

steps/NpmPublish/validate.json
https://github.com/Shippable/pm/issues/12629
=> Add validate.json for NpmPublish type steps

steps/GoBuild/execution/onExecute/onExecute.sh, steps/GoBuild/validate.json
=> Update JSON schema and script for GoBuild

steps/PromoteBuild/execution/onExecute/onExecute.sh, steps/PublishBuildInfo/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12615
verified
---
**publish**
=> update onExecute scripts of PublishBuildInfo and PromoteBuild to look from configuration instead of setup

steps/PushArtifactoryPackage/execution/onExecute/onExecute.sh, steps/PushArtifactoryPackage/validate.json
=> Update JSON schema and script for PushArtifactoryPackage

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh
closes https://github.com/Shippable/pm/issues/12613
=> use array envs

steps/NpmBuild/execution/onExecute/onExecute.sh, steps/NpmPublish/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12629
=> add onExecute.sh for processing NpmPublish steps

steps/XrayScan/execution/onExecute/onExecute.sh, steps/XrayScan/validate.json
closes https://github.com/Shippable/pm/issues/12619
=> use configuration instead of setup

steps/NpmBuild/execution/onExecute/onExecute.sh, steps/NpmPublish/execution/onExecute/onExecute.sh
=> Fix NpmBuild to save JFrog CLI state

steps/GoPublish/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/364
=> add validate.json for GoPublish step

steps/NpmBuild/execution/onExecute/onExecute.sh, steps/NpmPublish/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12629
=> update NpmBuild step to fetch files if FileSpec resource is added

resources/VmCluster/dependsOn.sh
=> Add sshKey handling for VmCluster

steps/MvnBuild/execution/onExecute/onExecute.sh, steps/NpmBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12629
=> Fix files not being copied error

steps/GoPublish/execution/onExecute/onExecute.sh, steps/GoPublish/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/364
GoPublish step ran successfully: 
Also published go packages in artifactory:
=>  add execution script for goPublish

resources/VmCluster/dependsOn.sh
=> Fix newlines in VmCluster sshKey

steps/PromoteBuild/validate.json
https://github.com/Shippable/pm/issues/12671
=> update PromoteBuild step to not require inputSteps

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/380
=> fix aql query for multiple buildInfo resources

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/382
=> enable usage of envs in configuration section

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/382
=> support spaces in releaseBundleName & releaseBundleVersion

steps/PublishBuildInfo/execution/onExecute/onExecute.sh, steps/PublishBuildInfo/validate.json
=> enhance PublishBuildInfo

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/CreateReleaseBundle/validate.json
#395 
Requires `outputResources`, with exactly one resource, and makes `integrations` optional.
=> #395; updates CreateReleaseBundle.

steps/Bash/header.sh
=> fix openjdk java path

steps/NpmBuild/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/398
=> remove required property on integrations for NpmBuild:

steps/PromoteBuild/validate.json
https://github.com/Shippable/pm/issues/12685
=> Update PromoteBuild's validate.json for new YML changes

steps/PromoteBuild/execution/onExecute/onExecute.sh, steps/PromoteBuild/validate.json
https://github.com/Shippable/pm/issues/12685
=> Update PromoteBuild's execute.sh to use input BuildInfo resource's integration

steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh, steps/DistributeReleaseBundle/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/405
closes https://github.com/Shippable/kermit-execTemplates/issues/404
=> updates validation & script for DistributeReleaseBundle

steps/GoBuild/execution/onExecute/onExecute.sh, steps/GoBuild/validate.json
=> Make GoBuild work with new constraints

steps/NpmBuild/execution/onExecute/onExecute.sh, steps/NpmBuild/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/398
If fileSpec resource is given as IN
If filespec resource is not present
=> Authenticate with fileSpec resource if present for NpmBuild

steps/NpmPublish/execution/onExecute/onExecute.sh, steps/NpmPublish/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/401
```yml
- name: start_npm_pub_xray_on
type: NpmPublish
configuration:
repositoryName: vishnu-npm-local
forceXrayScan: true
inputSteps:
- name: start_npm_build_1
integrations:
- name: art
- name: start_npm_pub_xray_off
type: NpmPublish
configuration:
repositoryName: vishnu-npm-local
forceXrayScan: false
inputSteps:
- name: start_npm_build_2
integrations:
- name: art
- name: start_npm_pub_xray_default
type: NpmPublish
configuration:
repositoryName: vishnu-npm-local
inputSteps:
- name: start_npm_build_3
integrations:
- name: art
```
=> adds forceXrayScan in NpmPublish

steps/DockerPush/validate.json, steps/PromoteBuild/validate.json
=> add validate.json for DockerPush step

steps/DockerBuild/execution/onExecute/onExecute.sh, steps/DockerBuild/validate.json
=> Update JSON schema and script for updated DockerBuild

steps/MvnBuild/execution/onExecute/onExecute.sh, steps/MvnBuild/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/415
=> validation & script for MvnBuild

steps/NpmPublish/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/418
=> adds autoPublishBuildInfo for NpmPublish step

steps/GoPublishModule/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/413
yaml: https://github.com/deepikasl/jpipe/blob/GoPublishBuild/GoPublishModule.yml
=> update GoPublishModule script to handle autoPublishBuildInfo

steps/NpmPublish/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/421
=> Publishes build info for NpmPublish

steps/Bash/header.sh
=> use new env

steps/DockerPush/execution/onExecute/onExecute.sh
=> add onExecute.sh for DockerPush step

steps/DockerBuild/execution/onExecute/onExecute.sh
=> Fix bug in DockerBuild step

steps/GoPublishBinary/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/427
https://docs.google.com/document/d/1LRPTVgKxI0iatzLlowdb5hWc1fklUVFE4kdLI-FV1lQ/edit
=> remove fileLocation, fileName and make targetRepository required

steps/DockerPush/execution/onExecute/onExecute.sh, steps/GoPublishModule/execution/onExecute/onExecute.sh, steps/NpmPublish/execution/onExecute/onExecute.sh
=> Save state in DockerPush step and correct scan order

resources/Image/dependsOn.sh
=> Allow image resource to work with Artifactory integration

steps/Bash/validate.json, steps/CreateReleaseBundle/validate.json, steps/DockerBuild/validate.json, steps/GoBuild/validate.json, steps/GoPublishBinary/validate.json, steps/GoPublishModule/validate.json, steps/NpmBuild/validate.json, steps/NpmPublish/validate.json, steps/PublishBuildInfo/validate.json, steps/PushArtifactoryPackage/validate.json, steps/SignReleaseBundle/validate.json, steps/XrayScan/validate.json
1. Some of the steps are missing environmentVariables and runtime sections, added in these in those.
2. Removed execution.onExecute section from DockerBuild and XrayScan
=> Fix validation for steps

steps/GoBuild/execution/onExecute/onExecute.sh, steps/GoPublishBinary/execution/onExecute/onExecute.sh, steps/GoPublishBinary/validate.json, steps/GoPublishModule/execution/onExecute/onExecute.sh, steps/GoPublishModule/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/427
**GoBuild -> GoPublishBinary**
**GoBuild -> Bash -> GoPublishBinary**
=> add execute script for GoPublishBinary

steps/Bash/header.sh
=> can change lang c

steps/NpmPublish/validate.json
https://github.com/Shippable/pm/issues/12733
=> add missing paranthesis in NpmPublish validate json

steps/Bash/header.sh
https://github.com/Shippable/kermit-execTemplates/issues/446
=> error write_output if user is trying to write to input resource

resources/Image/validate.json, resources/KubeCluster/validate.json, resources/RemoteFile/validate.json, resources/Webhook/validate.json
#448 
Adds remaining `validate.json` files for resources.
=> #448; adds remaining resource validate.json files.

steps/Bash/header.sh, steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/DockerBuild/execution/onExecute/onExecute.sh, steps/DockerPush/execution/onExecute/onExecute.sh, steps/GoBuild/execution/onExecute/onExecute.sh, steps/GoPublishBinary/execution/onExecute/onExecute.sh, steps/GoPublishModule/execution/onExecute/onExecute.sh, steps/GradleBuild/execution/onExecute/onExecute.sh, steps/MvnBuild/execution/onExecute/onExecute.sh, steps/NpmBuild/execution/onExecute/onExecute.sh, steps/NpmPublish/execution/onExecute/onExecute.sh, steps/PublishBuildInfo/execution/onExecute/onExecute.sh, steps/PushArtifactoryPackage/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/execution/onExecute/onExecute.sh
=> rename header funcs

steps/PromoteBuild/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/454
```yml
pipeline:
- name: pipe1
steps:
- name: promote
type: PromoteBuild
configuration:
#inherits from bash
targetRepository: <string>
includeDependencies: <boolean>    # default false
status: <string>                  # optional
comment: <string>                 # optional
copy: <boolean>                   # optional
- name: my_build_info           # required, only ONE allowed
trigger: false    
- name: my_output_build_info    # required, only ONE allowed
```
=> add new properties status, comment, copy to the PromoteBuild schema

steps/PromoteBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/454
=> update script to ihandle opy, status, comment iif given in yml

steps/PromoteBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/454
```yml
- name: promote_build_go
type: PromoteBuild
configuration:
targetRepository: promoted_go_test
comment: "comment"
status: "ready"
copy: true
includeDependencies: true
integrations:
- name: art
- name: go_build_info_publish
- name: promoted_go_build_info_go_publish
```
**Before**:
**After**:
=> append --copy and --include-dependencies only if they are true

steps/PromoteBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/454
=> refactor the if condition

steps/Bash/setup/runtime/image/image.sh
https://github.com/Shippable/pm/issues/12828
=> don't use status dir

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh, steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/464
A full flow of native steps pass with the support of artifactory and distribution integrations at respective places.
=> Uses Distribution integration instead of Artifactory integration

steps/DistributeReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/467
=> update releaseBundleName and releaseBundleVersion of the output ReleaseBundle if present

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/469
=> updates aql used in CreateReleaseBundle

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/471
=> update CreateReleaseBundle script to update output resource ReleaseBundle only if dryRun is false

steps/Bash/validate.json, steps/CreateReleaseBundle/validate.json, steps/DistributeReleaseBundle/validate.json, steps/DockerBuild/validate.json, steps/DockerPush/validate.json, steps/GoBuild/validate.json, steps/GoPublishBinary/validate.json, steps/GoPublishModule/validate.json, steps/GradleBuild/validate.json, steps/MvnBuild/validate.json, steps/NpmBuild/validate.json, steps/NpmPublish/validate.json, steps/PromoteBuild/validate.json, steps/PublishBuildInfo/validate.json, steps/PushArtifactoryPackage/validate.json, steps/SignReleaseBundle/validate.json, steps/XrayScan/validate.json
=> update validate.json for each step for custom private images

pipelines/validate.json, steps/DistributeReleaseBundle/validate.json
=> update validate.json for pipelines for custom private images

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/480
=> update CreateReleaseBundle script to allow markdown synatx

integrations/artifactory/cleanup.sh, integrations/artifactory/configure.sh
#485 
Adds scripts for Artifactory integrations.  Only the configured credentials are removed, and the config created is named with the integration name.
=> #485; adds scripts for Artifactory integrations.

integrations/gcloudKey/cleanup.sh, integrations/gcloudKey/configure.sh
#487 
Adds integration scripts to authenticate with and revoke gcloudKey integrations.
=> #487; adds scripts for gcloudKey integrations.

integrations/amazonKeys/cleanup.sh, integrations/amazonKeys/configure.sh
#483 
Adds scripts to configure and remove amazonKeys integration credentials.
=> #483; adds amazonKeys integration scripts.

integrations/kubernetesConfig/cleanup.sh, integrations/kubernetesConfig/configure.sh
#491 
Adds scripts to configure a kubernetesConfig integration for a step.  Confirmed that the file is created, found by kubectl, and read.
=> #491; adds scripts for kubernetesConfig integrations.

resources/KubeCluster/dependsOn.sh
https://github.com/Shippable/kermit-execTemplates/issues/493
**Before**:
**After fix**:
=> update KubeCluster resource script to preserve white space of config

steps/Bash/validate.json, steps/CreateReleaseBundle/validate.json, steps/DistributeReleaseBundle/validate.json, steps/DockerBuild/validate.json, steps/DockerPush/validate.json, steps/GoBuild/validate.json, steps/GoPublishBinary/validate.json, steps/GoPublishModule/validate.json, steps/GradleBuild/validate.json, steps/MvnBuild/validate.json, steps/NpmBuild/validate.json, steps/NpmPublish/validate.json, steps/PromoteBuild/validate.json, steps/PublishBuildInfo/validate.json, steps/PushArtifactoryPackage/validate.json, steps/SignReleaseBundle/validate.json, steps/XrayScan/validate.json
=> add "region" setting for custom image on ECR

steps/Bash/setup/runtime/image/image.sh
=> login to docker if custom image registry integration is provided

steps/Bash/setup/runtime/image/image.sh
=> logout from docker registry providers after booting container

resources/Webhook/output.sh
#498 
Sends JSON instead of text.
Tested with values containing spaces and quotes:
```JSON
{
"key":"value123",
"key2":"value456",
"key3":"testing 123",
"key4":"testing \"23",
"key5":"testing'"
}
```
=> #498; converts webhook payloads to JSON.

steps/Bash/setup/runtime/image/image.sh
=> logout from docker for all private custom image providers

steps/CreateReleaseBundle/validate.json, steps/DistributeReleaseBundle/validate.json, steps/DockerBuild/validate.json, steps/DockerPush/validate.json, steps/GoBuild/validate.json, steps/GoPublishBinary/validate.json, steps/GoPublishModule/validate.json, steps/GradleBuild/validate.json, steps/MvnBuild/validate.json, steps/NpmBuild/validate.json, steps/NpmPublish/validate.json, steps/PromoteBuild/validate.json, steps/PublishBuildInfo/validate.json, steps/PushArtifactoryPackage/validate.json, steps/SignReleaseBundle/validate.json, steps/XrayScan/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/508
=> update validate json of all steps to show correct error message for invalid runtime.type

resources/Aql/validate.json, resources/GitRepo/validate.json, resources/Image/validate.json, resources/KubeCluster/validate.json, resources/RemoteFile/validate.json, resources/Webhook/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/513
```yml
resources:
- name: all_git_Repo
type: GitRepo
randomKey: randomValue
configuration:
gitProvider: github
path: scriptnull/project-examples
```
```yml
resources:
- name: all_git_Repo
type: GitRepo
configuration:
randomKey: randomValue
gitProvider: github
path: scriptnull/project-examples
```
=> Adds additionalProperties at required spots

resources/RemoteFile/dependsOn.sh
https://github.com/Shippable/kermit-execTemplates/issues/520
Please check if the error message is legible.
=> handles unsupported protocol in RemoteFile resource script

Dockerfile
=> new dockerfile for sync image

Dockerfile
=> wrong character

steps/Bash/header.sh
https://github.com/Shippable/kermit/issues/2421
=> User can give % in command under onExecute section of bash

resources/FileSpec/dependsOn.sh
https://github.com/Shippable/kermit-execTemplates/issues/527
=> fail step if the given pattern doesn't exist
