Shippable/kermit-execTemplates

steps/bash/header.sh
#47 
Adds `switch_env`, copying `shippable_jdk` and leaving space to add more languages.
=> #47; adds switch_env with Java.

steps/bash/header.sh
#51 
Copies Ruby to `switch_env`.  Adds a `--jdk` option for `jruby` and a `--bundler` option.  The `--jdk` option is required for `jruby-head` and optional for everything else.
=> #51; copies Ruby to switch_env.

steps/bash/header.sh
#54 
The version cannot be set for Scala, Clojure, gcc, and clang.  This adds those and makes the version optional in `switch_env` and still required in all other languages.  The options (`--jdk` and `--bundler`) can also be before or after the version now.
=> #54; adds languages without versions to switch_env.

steps/bash/header.sh
#75 
Adds a function to copy test reports to later be parsed.  The reports may be files or directories.  The path will need to be updated somewhat later; right now the step and steplet IDs are the same, but they may not be in the future, and when we have more information available during the step, we can use the stepletId instead.
=> #75; adds save_tests to header.

steps/bash/header.sh
#81 
Caches both files and directories.  Wildcards also work.  If does not check that the file or directory exists before copying because the error message from `cp` is very reasonable (`cp: cannot stat 'doesnotexist.txt': No such file or directory`) and the wildcards were already becoming complicated.  The line to get the last parameter is bash-only, but this is for `bash` steps.
`cache_files my/file/path myCacheName`
=> #81; adds cache_files to header.

steps/bash/header.sh
https://github.com/Shippable/kermit-execTemplates/issues/86
updating the status code from 299 to 199 because, docker wait command doesn't return status code above 255 correctly
=> update status code on IN processing failure to 199

steps/bash/setup/runtime/image/image.sh
#91 
Adds a `RUN_DIR` volume mount, which was confirmed to be correct with `docker inspect`.
=> #91; adds RUN_DIR volume mount.

steps/bash/header.sh
#93 
Adds variables to `run.env`, creating it if `run.env` does not exist.
=> #93; adds add_run_variable.

steps/bash/setup/environmentVariables/footer.sh
#94 
The environment variables are available in `onStart` and `onExecute`, and should be available in `onSuccess` and `onFailure` as well.
=> #94; sources run.env.

resources/gitRepo/clone.sh
#132 
Similar to the scripts used by rSync.  The `.ssh/config` was in the u16microbase image, but I couldn't find a way to put it in the distroless image.
=> #132; adds new gitRepo clone script.

steps/bash/header.sh
#149 
The "name" can't be configured (no equivalent option in GitHub), so it's the step name right now.  Confirmed that each webhook type works, and multiple statuses can be added with different `--context` options.
=> #149; adds Bitbucket Cloud commit status.

steps/bash/header.sh
#151 
Only adds `bitbucketServerBasicAuth` because the other Bitbucket Server integration appears to have been removed.
Confirmed that statuses can be updated for commit, pull request, and tag webhooks.
=> #151; adds bitbucketServerBasicAuth to update_commit_status.

steps/bash/execution/onComplete/header.sh, steps/bash/execution/onExecute/header.sh, steps/bash/execution/onFailure/header.sh, steps/bash/execution/onStart/header.sh, steps/bash/execution/onSuccess/header.sh, steps/bash/header.sh
#153 
Checked statuses sent from each section.  When `onSuccess` fails, it does not continue to `onComplete`.
=> #153; adds default commit statuses to update_commit_status.

steps/bash/header.sh, steps/bash/setup/environmentVariables/footer.sh
#171 
Exports any environment variables in `pipeline.env`, if such a file exists.  Just like `run.env`.
=> #171; sources pipeline environment variables.

steps/bash/header.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/179
=> don't print the command on retry

steps/bash/header.sh
#191 
Changes the fragment size for file and string encryption.  Tested with large and small files and a string.  All appeared to decrypt correctly after they were encrypted.
=> #191; changes fragment size for encryption.

steps/powershell/footer.ps1
https://github.com/Shippable/kermit-execTemplates/issues/200
When we leave out onStart, onExecute, onSuccess, onFailure, onComplete sections in the YML, the respective functions(commands) are not generated for execution. So, we need to check each command before executing them.
```yml
- name: test_basic_execute
type: powershell
requires:
steps:
- start
execution:
onExecute:
- Write-Output "hi"
- name: test_basic_full_execute
type: powershell
requires:
steps:
- start
execution:
onStart:
- Write-Output "starting onStart"
- Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
onExecute:
- Write-Output "starting onExecute"
- Write-Output "CURRENT_SCRIPT_SECTION = $env:CURRENT_SCRIPT_SECTION"
onSuccess:
- Write-Output "starting onSuccess"
- Write-Output "CURRENT_SCRIPT_SECTION = …
```
=> adds check for commands before executing

steps/bash/setup/runtime/image/image.sh
#235 
Pulls the runtime image before `docker run` to be sure it is the latest.
Already present:
Pulling custom image:
Default `auto` image:
=> #235; pulls the runtime image.

steps/bash/validate.json, steps/build/validate.json, steps/promote/validate.json, steps/publish/validate.json, steps/push/validate.json
#240 
Removes encrypted sections.  Validation still works on each resource type without encrypted variables.
=> #240; removes encrypted variable sections.

steps/bash/header.sh
#267 
Since every resource should have a `resourceId`, this uses that to determine if the resource actually exists.
=> #267; adds a new error message for update_commit_status.

steps/Distribute/execution/onExecute/onExecute.sh, steps/Distribute/validate.json
closes https://github.com/Shippable/kermit-execTemplates/issues/288
tracker_id is always a `long` type. Confirmed with the Distribution team. A distribution can have the status `Not distributed` if the distribution is not scheduled yet.
=> add script to distribute a release bundle

steps/bash/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/282
Adding pipeline source with the following YML results in pipeline sync failure.
```yml
- name: test_3_pm_12569
type: bash
triggeredBy:
steps:
- start_pm_12569
setup:
runtime:
type: host
image:
auto:
language: nodejs
versions: 
- 8.16.0
execution:
onExecute:
- echo "hi"
```
=> updates validate.json for bash step

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
closes #314
produces same output as the old code given the same input (in the new format)
old
```json
{
"aql": "whatisthis",
"query_name": "stuff",
"mappings": [
{
"input": "hello",
"output": "world"
},
{
"input": "foo",
"output": "bar"
}
],
"added_props": []
}
```
new
```json
{
"aql": "whatisthis",
"query_name": "stuff",
"mappings": [
{
"input": "hello",
"output": "world"
},
{
"input": "foo",
"output": "bar"
}
],
"added_props": []
}
```
=> update onExecute script for aql

steps/PushArtifactoryPackage/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/336
All the below tests are done without "adds more required variable" commit, as `inputStep` is not being allowed currently due to a bug in pipelinesync which is being addressed in another PR.
```yml
resources:
- name: gitrepo_1
type: GitRepo
configuration:
gitProvider: github
path: scriptnull/jp
sha: sample-gitRepo-1
- name: img_1
type: Image
configuration:
registry: dockerint
imageName: scriptnull/custom
imageTag: develop
pipelines:
- name: test_pipeline
steps:
- name: push_to_art_2
type: PushArtifactoryPackage 
configuration:
targetRepo: "example"
forceXrayScan: false
autoPublishBuildInfo: false
npmArgs: ""
- name: gitrepo_1
integrations:
- name: artifactoryint
- name: img_1
```
=> Validates PushArtifactoryPackage

steps/SignReleaseBundle/validate.json
#339 
Both `integrations` and `inputResources` are required.  The `dryRun` option will not be added after all.
=> #339; updates SignReleaseBundle validation.

steps/Bash/header.sh
closes #360
since step_name and step_id are official read-only variables, we can just remove the lines that attempt to define them again.
=> use existing values

steps/GradleBuild/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/369
```yml
resources:
- name: gitrepo_1
type: GitRepo
configuration:
gitProvider: github
path: scriptnull/jp
sha: jfrog-samples
pipelines:
- name: test_pipeline
steps:
- name: start
type: GradleBuild
configuration:
gradleCommand: clean build -b build.gradle
sourceLocation: ./gradle-examples/gradle-example-minimal
configFileLocation: .
configFileName: gradle-art-config
- name: gitrepo_1
integrations:
- name: art
execution:
onStart:
- apt install default-jdk
- wget https://gradle.org/next-steps/?version=5.4.1&format=bin
- mkdir /opt/gradle
- unzip -d /opt/gradle gradle-5.4.1-bin.zip
- ls /opt/gradle/gradle-5.4.1
- export PATH=$PATH:/opt/gradle/gradle-5.4.1/bin
```
```yml
- name: missing_required
type: GradleBuild …
```
=> Adds validate.json for GradleBuild

steps/MvnBuild/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/369
Found out that MvnBuild is allowing `onExecute` section while referring its validate.json script for developing GradleBuild. So fixing it.
```yml
- name: build_mvn
type: MvnBuild
configuration:
sourceLocation: ./artifactory-maven-plugin-example
mvnCommand: clean install -f ./pom.xml
configFileLocation: .
configFileName: mvn-art-config
inputSteps:
- name: start
- name: gitrepo_1
integrations:
- name: art
execution:
onStart:
- apt install default-jdk
- pushd /tmp
- wget http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
- tar xzvf apache-maven-3.6.1-bin.tar.gz
- export PATH=$PATH:/tmp/apache-maven-3.6.1/bin
- export M2_HOME=/tmp/apache-maven-3.6.1/
- popd
- javac …
```
=> removes onExecute from MvnBuild

steps/Bash/header.sh
#374 
Fixes the path for the `replicate.json`.
=> #374; fixes replicate.json path.

steps/GradleBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/376
```yml
resources:
- name: git_project
type: GitRepo
configuration:
gitProvider: github
path: scriptnull/project-examples
sha: master
pipelines:
- name: test_pipeline
steps:
- name: start
type: GradleBuild
configuration:
gradleCommand: clean artifactoryPublish -b build.gradle
sourceLocation: gradle-examples/gradle-example-minimal
configFileLocation: .
configFileName: gradle-art-config
- name: git_project
integrations:
- name: art
runtime:
type: host
execution:
onStart:
- ls -la /opt
- uname -a
- export PATH=$PATH:/opt/gradle/gradle-5.4.1/bin
```
=> adds onExecute for GradleBuild

steps/Bash/header.sh
#386 
Changes the green color used as a default in notifications on success.
=> #386; updates green color.

steps/SignReleaseBundle/execution/onExecute/onExecute.sh, steps/SignReleaseBundle/validate.json
#389 
Updates SignReleaseBundle to make `integrations` optional and require one input resource and one output.
=> #389; updates SignReleaseBundle.

steps/XrayScan/execution/onExecute/onExecute.sh, steps/XrayScan/validate.json
#391 
Updates XrayScan validation and script.  This uses `replicate_resource` so that the `buildNumber` won't be converted to a string.
=> #391; updates XrayScan.

steps/GoPublishModule/execution/onExecute/onExecute.sh, steps/GoPublishModule/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/413
when autoPublishBuildInfo is set to true and no output resource is present
able to sync
=> update validate json of GoPublishModule to accept forceXrayScan and autoPublishBuildInfo

steps/GoPublishModule/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/413
I couldn't verify it locally because mill.jfrog.com is not configured with Xray
=> update GoPublishModule script to handle forceXrayScan

steps/PublishBuildInfo/validate.json
#393
this should allow the user to give inputResources, though they will not be used for anything in the native step, other than as potential triggers, or in the user's person scripts (onStart, onSuccess, onFailure, onComplete)
=> allow resources in PublishBuildInfo

steps/GradleBuild/execution/onExecute/onExecute.sh, steps/GradleBuild/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/426
Xray scan fails as the testing artifactory instance is not configured with Xray yet.
=> Adds forceXrayScan for GradleBuild

steps/GoPublishBinary/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/427
```yaml
pipeline:
- name: pipe1
steps:
- name: test_step_1
type: GoPublishBinary
configuration:
#inherits from bash
forceXrayScan: <boolean>          # default is false
autoPublishBuildInfo: <boolean>   # default is false
fileLocation: <string>            # required if not preceeded by GoBuild
fileName: <string>                # required if not preceeded by GoBuild
targetRepository: <string>        # required if not preceeded by GoBuild
inputSteps:                       # either one of Bash or GoBuild is required
- name: myBashStep         
- name: GoBuildStep         
integrations:
- name: art                     # required, exactly ONE
- name: BuildInfo               # required if autoPublishBuildInfo is true …
```
=> add validate json for GoPublishBinary

steps/GradleBuild/execution/onExecute/onExecute.sh, steps/GradleBuild/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/430
`outputBuildInfoResourceName` env will be exported in upcoming PR (in which we will injectEnvs in pipelineSync for GradleBuild)
=> adds autoPublishBuildInfo to GradleBuild step

pipelines/validate.json, steps/Bash/validate.json, steps/CreateReleaseBundle/validate.json, steps/DistributeReleaseBundle/validate.json, steps/DockerBuild/validate.json, steps/DockerPush/validate.json, steps/GoBuild/validate.json, steps/GoPublishBinary/validate.json, steps/GoPublishModule/validate.json, steps/GradleBuild/validate.json, steps/MvnBuild/validate.json, steps/NpmBuild/validate.json, steps/NpmPublish/validate.json, steps/PromoteBuild/validate.json, steps/PublishBuildInfo/validate.json, steps/PushArtifactoryPackage/validate.json, steps/SignReleaseBundle/validate.json, steps/XrayScan/validate.json
#450 
Makes `auto` or `custom` required in `image` (`image` is not required) and does not allow both `auto` and `custom` for all steps.
=> #450; makes auto or custom required and doesn't allow both.

resources/DistributionRule/validate.json, resources/ReleaseBundle/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/463
Added a commit with the check for additional properties in ReleaseBundle. Verified it with the following YML.
```yml
resources:
- name: fail_rb
type: ReleaseBundle
configuration:
sourceArtifactory: art
name: unsigned_release_bundle_mvn
version: v0.0.1
isSigned: false
```
=> Allows sourceDistribution instead of sourceArtifactory

steps/PromoteBuild/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/477
```yaml
- name: promote_build_go
type: PromoteBuild
configuration:
targetRepository: promote-test
comment: "comment test"
status: "ready"
copy: true
includeDependencies: true
integrations:
- name: art
- name: go_build_info_publish
- name: promoted_go_build_info_go_publish
```
=> update PromoteBuild script to use array instead of string to allow multi-word seperated by space

integrations/sshKey/cleanup.sh, integrations/sshKey/configure.sh
#489 
Adds SSH keys in the same way as for clusters with sshKey integrations and removes the keys at the end of the step.
=> #489; adds scripts to add and remove sshKeys.

steps/Bash/validate.json, steps/CreateReleaseBundle/validate.json, steps/DistributeReleaseBundle/validate.json, steps/DockerBuild/validate.json, steps/DockerPush/validate.json, steps/GoBuild/validate.json, steps/GoPublishBinary/validate.json, steps/GoPublishModule/validate.json, steps/GradleBuild/validate.json, steps/MvnBuild/validate.json, steps/NpmBuild/validate.json, steps/NpmPublish/validate.json, steps/PromoteBuild/validate.json, steps/PublishBuildInfo/validate.json, steps/PushArtifactoryPackage/validate.json, steps/SignReleaseBundle/validate.json, steps/XrayScan/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/479
https://github.com/Shippable/heap/issues/3499 reports that `auto` field is not restricting additional properties. The last commit of this PR fixes it.
=> Updates validation for auto and custom fields

resources/Image/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/500
```yml
resources:
- name: ecr_image
type: Image
configuration:
registry: aws
imageName: 854172162208.dkr.ecr.us-east-1.amazonaws.com/sample/custom
imageTag: latest
region: us-east-1
pipelines:
- name: img_pipeline
steps:
- name: sample_img
type: Bash
configuration:
runtime:
type: image
image:
custom:
name: drydock/u16node
tag: master
- name: ecr_image
execution:
onExecute:
- sudo docker images
- test "$res_ecr_image_region" == "us-east-1" 
```
=> allows region in Image resource

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/pm/issues/12843
CreateReleaseBundle is failing if we don't mention dryRun in the yaml. This is because of a typo while assigning dryRun true.
Instead of `$dryRun=true` it should be `dryRun=true`
=> assign dryRun to true if its not mentioned in yaml

steps/Bash/header.sh
#506 
Changes the default `opt_username` used for Slack, Airbrake, and New Relic.
=> #506; changes default opt_username to JFrog Pipelines.

steps/CreateReleaseBundle/execution/onExecute/onExecute.sh
https://github.com/Shippable/kermit-execTemplates/issues/504
When the artifactory integration does not have enough permissions (i.e. admin permission in artifactory), the CreateReleaseBundle behaves as mentioned below.
=> checks for errors while getting Artifactory service id

steps/Bash/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/508
```yaml
runtime:
type: foobar
```
```yaml
runtime:
type: host
image:
custom:
name: test
tag: test
```
```yaml
runtime:
type: image
image:
custom:
name: test
tag: test
language: test
```
```yaml
runtime:
type: image
image:
custom:
language: test
```
=> update validate json of Bash step to show correct error message for invalid runtime.type

steps/Bash/header.sh
closes https://github.com/Shippable/kermit-execTemplates/issues/511
=> support status flag in send_notification

resources/BuildInfo/validate.json
https://github.com/Shippable/kermit-execTemplates/issues/515
Currently missing sourceArtifactory results in two error messages, one from validate.json and one from pipelineSync's validateBuildInfo.js file. We will prefer using the message from validate.json and the PR for removing the check inside pipelineSync's validateBuildInfo.js will be opened after right after this.
=> marks sourceArtifactory as required for BuildInfo resource

resources/FileSpec/dependsOn.sh
https://github.com/Shippable/kermit-execTemplates/issues/527
when the given pattern file doesn't exist in artifactory
when file exists in artifactory
=> fail step if the given pattern doesn't exist

Dockerfile
#530 
Updates the scriptsbase Dockerfile to use both kermit and kermit-execTemplates repositories and the drydock/u18node base image.  Confirmed that the pipeline appears correct with the "dry run" option and that an image built from the Dockerfile can be used to run pipelineSync.
=> #530; updates scriptsbase Dockerfile.

resources/GitRepo/hookHandler/scripts/ApiAdapter.js, resources/GitRepo/hookHandler/scripts/bitbucket/validateWebhook.js, resources/GitRepo/hookHandler/scripts/bitbucketServer/validateWebhook.js, resources/GitRepo/hookHandler/scripts/github/validateWebhook.js, resources/GitRepo/hookHandler/scripts/gitlab/validateWebhook.js, resources/GitRepo/hookHandler/scripts/package.json, resources/GitRepo/hookHandler/scripts/runTypes.js, resources/GitRepo/hookHandler/scripts/validateWebhook.js, resources/GitRepo/hookHandler/validate.sh
#524 
Copies webhook validation to execTemplates for hookHandler.  Confirmed that a webhook for each provider still passes validation.  These will be further tested when the scripts to create resource versions are added.
=> #524; adds GitRepo webhook validation.
